export let gameDummyData = [
  {
    gameName: "Final Fantasy",
    developer: "Square Enix",
    gameDescription: "Some game description",
    gamePrice: 3000,
    currency: "руб",
    isInSale: true,
    gameSalePrice: 1500,
    images: ["./resources/images/ff/ff_1.jpg, ./resources/images/ff/ff_2.jpg"],
    videos: ["./resources/videos/ff/ff_1.mp4"],
  },
  {
    gameName: "Naruto",
    developer: "Bandai namco",
    gameDescription: "Some game description",
    gamePrice: 4000,
    currency: "руб",
    isInSale: false,
    gameSalePrice: null,
    images: [
      "./resources/images/naruto/naruto_1.jpg, ./resources/images/naruto/naruto_2.jpg",
    ],
    videos: ["./resources/videos/naruto/naruto_1.mp4"],
  },
  {
    gameName: "Dragon's Dogma",
    developer: "Campcom",
    gameDescription: "Some game description",
    gamePrice: 1500,
    currency: "руб",
    isInSale: true,
    gameSalePrice: 300,
    images: ["./resources/images/dd/dd_1.jpg, ./resources/images/dd/dd_2.jpg"],
    videos: ["./resources/videos/dd/dd_1.mp4"],
  },
  {
    gameName: "Dragon Quest",
    developer: "Square Enix",
    gameDescription: "Some game description",
    gamePrice: 2500,
    currency: "руб",
    isInSale: true,
    gameSalePrice: 1000,
    images: ["./resources/images/dq/dq_1.jpg, ./resources/images/dq/dq_2.jpg"],
    videos: ["./resources/videos/dq/dq_1.mp4"],
  },
  {
    gameName: "Doki Doki Literature club",
    developer: "Team Salvato",
    gameDescription: "Some game description",
    gamePrice: 0,
    currency: "руб",
    isInSale: false,
    gameSalePrice: null,
    images: [
      "./resources/images/ddlc/ddlc_1.jpg, ./resources/images/ddlc/ddlc_2.jpg",
    ],
    videos: ["./resources/videos/ddlc/ddlc_1.mp4"],
  },
  {
    gameName: "Fire Emblem",
    developer: "Nintendo",
    gameDescription: "Some game description",
    gamePrice: 5000,
    currency: "руб",
    isInSale: true,
    gameSalePrice: 2500,
    images: [
      "./resources/images/ddlc/ddlc_1.jpg, ./resources/images/ddlc/ddlc_2.jpg",
    ],
    videos: ["./resources/videos/ddlc/ddlc_1.mp4"],
  },
];
